# Generated by Django 4.1.1 on 2022-09-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('tipoUsuario', models.CharField(choices=[('PA', 'Paciente'), ('AC', 'Acudiente'), ('MD', 'Medico')], max_length=3, primary_key=True, serialize=False)),
                ('permisos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='Rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rol_id', to='authApp.rol'),
            preserve_default=False,
        ),
    ]
