# Generated by Django 4.1.1 on 2022-10-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_account_fechaingreso_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fechaIngreso',
        ),
    ]
