# Generated by Django 4.1.1 on 2022-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='idAcount',
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipoUsuario',
            field=models.CharField(choices=[('PA', 'Paciente'), ('AC', 'Acudiente'), ('MD', 'Medico'), ('EF', 'Enfermero')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email'),
        ),
    ]
