# Generated by Django 4.1.1 on 2022-09-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_rename_id_account_idacount_alter_rol_tipousuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='idAcount',
            new_name='id',
        ),
    ]
