# Generated by Django 4.1.1 on 2022-09-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_rename_idacount_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lastChangeDate',
            new_name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isActive',
        ),
        migrations.AddField(
            model_name='account',
            name='especializacion',
            field=models.CharField(default='%Y-%m-%d %H:%M:%S', max_length=100, verbose_name='Especializacion'),
            preserve_default=False,
        ),
    ]
