# Generated by Django 4.1.1 on 2022-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_rename_lastchangedate_account_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='descripcion',
            field=models.CharField(default='2006-10-25 14:30:59', max_length=250, verbose_name='Especializacion'),
            preserve_default=False,
        ),
    ]
